"""Prove the OKF v0.2 migration lost nothing, independently of the compiler.

For every note that declares itself generated by `migrate_policy_data.py`,
regenerate it from `policy_data.py` into a temporary directory and assert the
result is **byte-identical** to the note on disk.

This is a third, independent oracle on the same ~238 facts:

  1. `verify_policy_data.py`  -- figures in policy_data.py match text
                                 extracted from the source PDF.
  2. `verify_compile.py`      -- chunks emitted from the vault match the
                                 pre-OKF index, field by field.
  3. this                     -- the vault notes themselves are exactly what
                                 the generator produces, so no hand edit,
                                 encoding change or migration bug has drifted
                                 a single byte.

(2) would catch a changed figure, because chunk text carries it. It would
NOT catch a change to a field chunks do not use -- provenance, verification
actors, an ambiguity's disclosure text. That gap is what this closes.

Notes NOT stamped `generated.by: process:migrate_policy_data` are
hand-authored and have no generator to compare against. They are counted and
listed, never regenerated.

Run:  python -m app.okf.verify_migration
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

from app.okf import frontmatter as frontmatter_mod
from app.okf import migrate_policy_data as mpd
from app.okf import migrate_to_okf_v02, vault


def main() -> None:
    failures: list[str] = []

    records = (
        mpd.build_scheme() + mpd.build_incentives() + mpd.build_eligibility_rules()
        + mpd.build_districts() + mpd.build_sectors() + mpd.build_glossary()
        + mpd.build_ambiguities()
    )
    index = mpd._link_index(records)

    checked = 0
    missing: list[str] = []

    with tempfile.TemporaryDirectory() as tmp:
        tmp_root = Path(tmp)

        for entity_type, entity_id, raw_fm, body in records:
            folder = vault.ENTITY_FOLDERS[entity_type]
            on_disk = vault.VAULT_DIR / folder / f"{entity_id}.md"

            if not on_disk.exists():
                missing.append(f"{folder}/{entity_id}.md")
                continue

            payload = migrate_to_okf_v02.rewrite_frontmatter(
                {k: v for k, v in raw_fm.items() if k != "entity_type"}, index
            )
            okf = frontmatter_mod.to_okf_frontmatter(
                entity_type, payload, generated_by=mpd.GENERATOR_ACTOR
            )
            regenerated = tmp_root / folder / f"{entity_id}.md"
            vault.write_note(
                regenerated, okf, migrate_to_okf_v02.rewrite_body_links(body, index)
            )

            expected = regenerated.read_bytes()
            actual = on_disk.read_bytes()
            checked += 1
            if expected != actual:
                failures.append(
                    f"{folder}/{entity_id}.md is not byte-identical to a fresh "
                    f"regeneration ({len(actual)} bytes on disk vs {len(expected)} "
                    f"regenerated)"
                )

    for path in missing:
        failures.append(f"{path} should be generated by migrate_policy_data but is absent")

    # Every note the generator does NOT produce is hand-authored. Listing
    # them is the point: they are exactly the notes no automated check can
    # reconstruct, so they are also the ones a careless `--clean` would
    # destroy, and the ones a human has to review by reading.
    generated_paths = {
        vault.VAULT_DIR / vault.ENTITY_FOLDERS[t] / f"{i}.md"
        for t, i, _fm, _b in records
    }
    hand_authored = [
        n.path.relative_to(vault.VAULT_DIR)
        for n in vault.iter_notes()
        if n.path not in generated_paths
    ]

    for note in vault.iter_notes():
        stamped = (note.frontmatter.get("generated") or {}).get("by")
        is_generated = note.path in generated_paths
        if is_generated and stamped != mpd.GENERATOR_ACTOR:
            failures.append(
                f"{note.path.name} is reproducible by migrate_policy_data but is not "
                f"stamped generated.by={mpd.GENERATOR_ACTOR!r} (got {stamped!r}); "
                f"--clean would refuse to tidy it"
            )
        if not is_generated and stamped == mpd.GENERATOR_ACTOR:
            failures.append(
                f"{note.path.name} is NOT reproducible by migrate_policy_data but "
                f"claims generated.by={mpd.GENERATOR_ACTOR!r}; --clean would DELETE "
                f"it and nothing could restore it"
            )

    if failures:
        for f in failures[:40]:
            print(f"FAIL: {f}")
        if len(failures) > 40:
            print(f"... and {len(failures) - 40} more")
        print(f"\n{len(failures)} failure(s).")
        sys.exit(1)

    print(
        f"PASS: {checked} generated note(s) are byte-identical to a fresh "
        f"regeneration from policy_data.py; {len(hand_authored)} hand-authored "
        f"note(s) correctly carry no generator stamp, so --clean cannot delete them:"
    )
    for path in sorted(hand_authored):
        print(f"    {path}")


if __name__ == "__main__":
    main()
